cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('to_cart/<int:product_id>/<str:action>/', views.to_cart, name='to_cart'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('payment/', views.create_checkout_session, name='payment'),
    path('payment/success/', views.success_payment, name='success_payment')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('store.urls')),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from users.models import CustomUser
from store.models import Product


class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL,
                             null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_completed = models.BooleanField(default=False)

    @property
    def get_cart_total_price(self):
        products = self.orderproduct_set.all()
        return sum([product.get_total_price for product in products])

    @property
    def get_cart_total_quantity(self):
        products = self.orderproduct_set.all()
        return sum([product.quantity for product in products])


class OrderProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def get_total_price(self):
        return self.product.price * self.quantity


class Customer(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    email = models.EmailField(verbose_name='Почта')
    phone_number = models.CharField(max_length=15, verbose_name='Номер телефона')
    company_name = models.CharField(max_length=100, verbose_name='Название компании')
    country = models.CharField(max_length=100, verbose_name='Страна')
    address_1 = models.CharField(max_length=150, verbose_name='Адрес 1')
    address_2 = models.CharField(max_length=150, verbose_name='Адрес 2')
    town = models.CharField(max_length=100, verbose_name='Город')
    state = models.CharField(max_length=100, verbose_name='Штат')

cart/forms.py
from .models import Customer
from django import forms


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ('pk',)
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Enter your name'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Enter your lastname'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Enter your email'
            }),
            'phone_number': forms.TextInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Enter your phone number'
            }),
            'company_name': forms.TextInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Enter your company name'
            }),
            'country': forms.TextInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Enter country'
            }),
            'address_1': forms.TextInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Enter address 1'
            }),
            'address_2': forms.TextInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Enter address 2'
            }),
            'town': forms.TextInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Enter town'
            }),
            'state': forms.TextInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'state'
            }),
        }

cart/views.py
from django.shortcuts import render, HttpResponse, redirect
from .utils import CartForAnonymousUser, CartForAuthenticatedUser, get_cart_data
from django.urls import reverse
from .forms import CustomerForm
import stripe
from shop import settings
# Create your views here.


def home_view(request):
    cart_info = get_cart_data(request)
    context = {
        'cart_total_quantity': cart_info['cart_total_quantity'],
        'cart_total_price': cart_info['cart_total_price'],
        'products': cart_info['products'],
        'order': cart_info['order']
    }

    return render(request, 'cart/cart.html', context)


def to_cart(request, product_id, action):
    if request.user.is_authenticated:
        user_cart = CartForAuthenticatedUser(request, product_id, action)
    else:
        session_cart = CartForAnonymousUser(request, product_id, action)

    return redirect('cart:home')


def checkout_view(request):
    cart_data = get_cart_data(request)

    if request.method == 'POST':
        form = CustomerForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('store:home')
    else:
        form = CustomerForm()
    context = {
        'form': form,
        'cart_total_price': cart_data['cart_total_price'],
        'products': cart_data['products']
    }
    return render(request, 'cart/checkout.html', context)


def create_checkout_session(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY

    if not request.user.is_authenticated:
        user_cart = CartForAnonymousUser(request)
    else:
        user_cart = CartForAuthenticatedUser(request)

    cart_info = user_cart.get_cart_info()
    total_price = cart_info['cart_total_price']

    session = stripe.checkout.Session.create(
        line_items=[
            {
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                        'name': 'Продукты с сайта Boutique'
                    },
                    'unit_amount': int(total_price * 100)
                },
                'quantity': 1
            }
        ],
        mode='payment',
        success_url=request.build_absolute_uri(reverse('cart:success_payment')),
        cancel_url=request.build_absolute_uri(reverse('cart:success_payment')),
    )

    print(session.url)
    return redirect(session.url, 303)


def success_payment(request):
    if request.user.is_authenticated:
        user_cart = CartForAuthenticatedUser(request)
    else:
        user_cart = CartForAnonymousUser(request)

    user_cart.clear()
    return HttpResponse('успешно')

cart/templates/cart/cart.html
{% extends 'base.html' %}

{% block title %}
Корзина
{% endblock %}

{% block content %}
<!-- HERO SECTION-->
<section class="py-5 bg-light">
    <div class="container">
        <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
            <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Cart</h1>
            </div>
            <div class="col-lg-6 text-lg-end">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-lg-end mb-0 px-0 bg-light">
                        <li class="breadcrumb-item"><a class="text-dark" href="index.html">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Cart</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>
<section class="py-5">
    <h2 class="h5 text-uppercase mb-4">Shopping cart</h2>
    <div class="row">
        <div class="col-lg-8 mb-4 mb-lg-0">
            <!-- CART TABLE-->
            <div class="table-responsive mb-4">
                <table class="table text-nowrap">
                    <thead class="bg-light">
                    <tr>
                        <th class="border-0 p-3" scope="col"><strong class="text-sm text-uppercase">Product</strong>
                        </th>
                        <th class="border-0 p-3" scope="col"><strong class="text-sm text-uppercase">Price</strong></th>
                        <th class="border-0 p-3" scope="col"><strong class="text-sm text-uppercase">Quantity</strong>
                        </th>
                        <th class="border-0 p-3" scope="col"><strong class="text-sm text-uppercase">Total</strong></th>
                        <th class="border-0 p-3" scope="col"><strong class="text-sm text-uppercase"></strong></th>
                    </tr>
                    </thead>
                    <tbody class="border-0">
                    {% for cart_product in products %}
                    <tr>
                        <th class="ps-0 py-3 border-light" scope="row">
                            <div class="d-flex align-items-center"><a class="reset-anchor d-block animsition-link"
                                                                      href="detail.html"><img
                                    src="{{ cart_product.product.get_preview }}" alt="..." width="70"/></a>
                                <div class="ms-3"><strong class="h6"><a class="reset-anchor animsition-link"
                                                                        href="{{ cart_product.product.get_absolute_url }}">{{ cart_product.product.name }}</a></strong></div>
                            </div>
                        </th>
                        <td class="p-3 align-middle border-light">
                            <p class="mb-0 small">${{ cart_product.product.price }}</p>
                        </td>
                        <td class="p-3 align-middle border-light">
                            <div class="border d-flex align-items-center justify-content-between px-3"><span
                                    class="small text-uppercase text-gray headings-font-family">Quantity</span>
                                <div class="quantity">
                                    <a href="{% url 'cart:to_cart' cart_product.product.pk 'delete' %}" class="dec-btn p-0"><i class="fas fa-caret-left"></i></a>
                                    <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text"
                                           value="{{ cart_product.quantity }}"/>
                                    <a href="{% url 'cart:to_cart' cart_product.product.pk 'add' %}" class="inc-btn p-0"><i class="fas fa-caret-right"></i></a>
                                </div>
                            </div>
                        </td>
                        <td class="p-3 align-middle border-light">
                            <p class="mb-0 small">${{ cart_product.get_total_price }}</p>
                        </td>
                        <td class="p-3 align-middle border-light"><a class="reset-anchor" href="#!"><i
                                class="fas fa-trash-alt small text-muted"></i></a></td>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            <!-- CART NAV-->
            <div class="bg-light px-4 py-3">
                <div class="row align-items-center text-center">
                    <div class="col-md-6 mb-3 mb-md-0 text-md-start"><a class="btn btn-link p-0 text-dark btn-sm"
                                                                        href="shop.html"><i
                            class="fas fa-long-arrow-alt-left me-2"> </i>Continue shopping</a></div>
                    <div class="col-md-6 text-md-end"><a class="btn btn-outline-dark btn-sm" href="{% url 'cart:checkout' %}">Procceed
                        to checkout<i class="fas fa-long-arrow-alt-right ms-2"></i></a></div>
                </div>
            </div>
        </div>
        <!-- ORDER TOTAL-->
        <div class="col-lg-4">
            <div class="card border-0 rounded-0 p-lg-4 bg-light">
                <div class="card-body">
                    <h5 class="text-uppercase mb-4">Cart total</h5>
                    <ul class="list-unstyled mb-0">
                        <li class="d-flex align-items-center justify-content-between"><strong
                                class="text-uppercase small font-weight-bold">Subtotal</strong><span
                                class="text-muted small">${{ cart_total_price }}</span></li>
                        <li class="border-bottom my-2"></li>
                        <li class="d-flex align-items-center justify-content-between mb-4"><strong
                                class="text-uppercase small font-weight-bold">Total</strong><span>${{ cart_total_price }}</span></li>
                        <li>
                            <form action="#">
                                <div class="input-group mb-0">
                                    <input class="form-control" type="text" placeholder="Enter your coupon">
                                    <button class="btn btn-dark btn-sm w-100" type="submit"><i
                                            class="fas fa-gift me-2"></i>Apply coupon
                                    </button>
                                </div>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

cart/templates/cart/checkout.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block title %}
Оформление заказа
{% endblock %}

{% block content %}
<!-- HERO SECTION-->
<section class="py-5 bg-light">
    <div class="container">
        <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
            <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Checkout</h1>
            </div>
            <div class="col-lg-6 text-lg-end">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-lg-end mb-0 px-0 bg-light">
                        <li class="breadcrumb-item"><a class="text-dark" href="index.html">Home</a></li>
                        <li class="breadcrumb-item"><a class="text-dark" href="cart.html">Cart</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Checkout</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>
<section class="py-5">
    <!-- BILLING ADDRESS-->
    <h2 class="h5 text-uppercase mb-4">Billing details</h2>
    <div class="row">
        <div class="col-lg-8">
            <form action="{% url 'cart:payment' %}" method="post">
                {% csrf_token %}

                <div class="row gy-3">
                    {% for field in form %}
                    {% check_field_class field as is_address %}
                    <div class="{% if not is_address %}col-lg-6{% else %}col-lg-12{% endif %}">
                        <label class="form-label text-sm text-uppercase" for="{{ field.id_for_label }}">{{ field.name }} </label>
                        {{ field }}
                    </div>
                    {% endfor %}

                    <div class="col-lg-12 form-group">
                        <button class="btn btn-dark" type="submit">Place order</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- ORDER SUMMARY-->
        <div class="col-lg-4">
            <div class="card border-0 rounded-0 p-lg-4 bg-light">
                <div class="card-body">
                    <h5 class="text-uppercase mb-4">Your order</h5>
                    <ul class="list-unstyled mb-0">
                        {% for item in products %}
                        <li class="d-flex align-items-center justify-content-between">
                            <strong class="small fw-bold">{{ item.product.name }}</strong>
                            <span class="text-muted small">${{ item.product.price }}</span>
                        </li>
                        <li class="border-bottom my-2"></li>
                        {% endfor %}

                        <li class="d-flex align-items-center justify-content-between"><strong
                                class="text-uppercase small fw-bold">Total</strong><span>${{ cart_total_price }}</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}