cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('to_cart/<int:product_id>/<str:action>/', views.to_cart, name='to_cart'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('payment/', views.create_checkout_session, name='payment'),
    path('payment/success/', views.success_payment, name='success_payment')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('store.urls')),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.home_view, name='home'),
    path('registration/', views.registration_view, name='registration'),
    path('logout/', views.user_logout, name='logout')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to='users/avatars/%Y/%M/%D', blank=True, null=True)

users/forms.py
from django import forms

from .models import CustomUser
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']


class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'avatar', 'password1', 'password2']

users/views.py
from django.shortcuts import render, HttpResponse, redirect
from .forms import LoginForm, RegistrationForm
from django.contrib.auth import authenticate, login, logout
# Create your views here.


def home_view(request):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('store:home')
    else:
        form = LoginForm()

    context = {
        'form': form
    }
    return render(request, 'users/login.html', context)


def registration_view(request):
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('users:home')
    else:
        form = RegistrationForm()

    context = {
        'form': form
    }
    return render(request, 'users/registration.html', context)


def user_logout(request):
    logout(request)
    return redirect('store:home')

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registration</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Montserrat:400,500&display=swap');

        body {
            font-family: Montserrat, Arial, Helvetica, sans-serif;
            background-color: #f7f7f7;
        }

        * {
            box-sizing: border-box
        }

        /* Add padding to container elements */
        .container {
            padding: 20px;
            width: 500px;
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            border: 1px solid #ccc;
            border-radius: 10px;
            background: white;
            -webkit-box-shadow: 2px 1px 21px -9px rgba(0, 0, 0, 0.38);
            -moz-box-shadow: 2px 1px 21px -9px rgba(0, 0, 0, 0.38);
            box-shadow: 2px 1px 21px -9px rgba(0, 0, 0, 0.38);
        }

        /* Full-width input fields */
        input[type=text],
        input[type=password] {
            width: 100%;
            padding: 15px;
            margin: 5px 0 22px 0;
            display: inline-block;
            border: none;
            background: #f7f7f7;
            font-family: Montserrat, Arial, Helvetica, sans-serif;
        }

        select {
            width: 18%;
            padding: 15px;
            margin: 5px 0 22px 0;
            display: inline-block;
            border: none;
            background: #f7f7f7;
            font-family: Montserrat, Arial, Helvetica, sans-serif;
        }

        input[type=phone] {
            width: 81%;
            padding: 15px;
            margin: 5px 0 22px 0;
            display: inline-block;
            border: none;
            background: #f7f7f7;
        }

        input[type=text]:focus,
        input[type=password]:focus,
        input[type=phone]:focus,
        select:focus {
            background-color: #ddd;
            outline: none;
        }

        button {
            background-color: #0eb7f4;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
            opacity: 0.9;
            font-size: 16px;
            font-family: Montserrat, Arial, Helvetica, sans-serif;
            border-radius: 10px;
        }

        button:hover {
            opacity: 1;
        }
    </style>
</head>

<body>
<form method="post" action="">
    {% csrf_token %}
    <div class="container">
        <h1>Login</h1>
        {{ form }}
        <p>Do not have account yet?. <a href="{% url 'users:registration' %}">Create account</a></p>

        <div class="clearfix">
            <button type="submit" class="btn">Login</button>
        </div>
    </div>
</form>
</body>

</html>

users/templates/users/registration.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registration</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Montserrat:400,500&display=swap');

        body {
            font-family: Montserrat, Arial, Helvetica, sans-serif;
            background-color: #f7f7f7;
        }

        * {
            box-sizing: border-box
        }

        .container {
            padding: 20px;
            width: 500px;
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            border: 1px solid #ccc;
            border-radius: 10px;
            background: white;
            -webkit-box-shadow: 2px 1px 21px -9px rgba(0, 0, 0, 0.38);
            -moz-box-shadow: 2px 1px 21px -9px rgba(0, 0, 0, 0.38);
            box-shadow: 2px 1px 21px -9px rgba(0, 0, 0, 0.38);
        }

        input[type=text],
        input[type=email],
        input[type=file],
        input[type=password] {
            width: 100%;
            padding: 15px;
            margin: 5px 0 22px 0;
            display: inline-block;
            border: none;
            background: #f7f7f7;
            font-family: Montserrat, Arial, Helvetica, sans-serif;
        }

        select {
            width: 18%;
            padding: 15px;
            margin: 5px 0 22px 0;
            display: inline-block;
            border: none;
            background: #f7f7f7;
            font-family: Montserrat, Arial, Helvetica, sans-serif;
        }

        input[type=phone] {
            width: 81%;
            padding: 15px;
            margin: 5px 0 22px 0;
            display: inline-block;
            border: none;
            background: #f7f7f7;
        }

        input[type=text]:focus,
        input[type=password]:focus,
        input[type=phone]:focus,
        select:focus {
            background-color: #ddd;
            outline: none;
        }

        button {
            background-color: #0eb7f4;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
            opacity: 0.9;
            font-size: 16px;
            font-family: Montserrat, Arial, Helvetica, sans-serif;
            border-radius: 10px;
        }

        button:hover {
            opacity: 1;
        }
    </style>
</head>

<body>
<form method="POST" enctype="multipart/form-data" action="">
    {% csrf_token %}
    <div class="container">
        <h1>Sign Up</h1>
        <p>Please fill in this form to create an account.</p>
        {% for field in form %}
            <div>
                {{ field.label }}
                {{ field }}
            </div>
            {% for error in field.errors %}
                <small style="color: red">{{ error }}</small>
            {% endfor %}
        {% endfor %}
        <p>Have an account?. <a href="{% url 'users:home' %}">Login</a></p>
        <div class="clearfix">
            <button type="submit" class="btn">Sign Up</button>
        </div>
    </div>
</form>
</body>

</html>